/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PublishingRouteImport } from './routes/publishing'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as ContentFactoryRouteImport } from './routes/content-factory'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishingRoute = PublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentFactoryRoute = ContentFactoryRouteImport.update({
  id: '/content-factory',
  path: '/content-factory',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/clips': typeof ClipsRoute
  '/content-factory': typeof ContentFactoryRoute
  '/learning': typeof LearningRoute
  '/publishing': typeof PublishingRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/clips': typeof ClipsRoute
  '/content-factory': typeof ContentFactoryRoute
  '/learning': typeof LearningRoute
  '/publishing': typeof PublishingRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/clips': typeof ClipsRoute
  '/content-factory': typeof ContentFactoryRoute
  '/learning': typeof LearningRoute
  '/publishing': typeof PublishingRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/billing'
    | '/clips'
    | '/content-factory'
    | '/learning'
    | '/publishing'
    | '/settings'
    | '/signin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/billing'
    | '/clips'
    | '/content-factory'
    | '/learning'
    | '/publishing'
    | '/settings'
    | '/signin'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/billing'
    | '/clips'
    | '/content-factory'
    | '/learning'
    | '/publishing'
    | '/settings'
    | '/signin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  ClipsRoute: typeof ClipsRoute
  ContentFactoryRoute: typeof ContentFactoryRoute
  LearningRoute: typeof LearningRoute
  PublishingRoute: typeof PublishingRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishing': {
      id: '/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof PublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-factory': {
      id: '/content-factory'
      path: '/content-factory'
      fullPath: '/content-factory'
      preLoaderRoute: typeof ContentFactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  ClipsRoute: ClipsRoute,
  ContentFactoryRoute: ContentFactoryRoute,
  LearningRoute: LearningRoute,
  PublishingRoute: PublishingRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
